# Generated by configure.pl on Wed Sep 26 18:40:54 2018
# DO NOT EDIT THIS FILE DIRECTLY!
# Change settings and rerun configure.pl instead

{
  'GOCADCONF' => 'release-Win_x64_6.1_v15',
  'PROJECT_RELEASE_DATE' => 'now',
  'GOCAD_CCMODE' => '',
  'GOCAD_OS' => 'Win_x64_6.1',
  'GOCAD_CC' => 'v15',
  'GOCAD_TARGET' => 'Win_x64_6.1_v15',
  'PROJECT_REQUIRES' => 'Gocad:3.0.0',
  'PROJECT_BUILD_DATE' => '20180926',
  'GOCAD_GR' => 'opengl',
  'GOCAD_BUILD_TYPE' => 'release',
  'PROJECT_SOURCE_CONTROL_PATH' => 'None',
  'PROJECT_BUILD_IDENTIFIER' => '20180926',
  'PROJECT_NAME' => 'PluginWindow',
  'GOCAD_PLATFORM' => 'Win_x64_6.1_v15',
  'GOCADHOME' => 'C:/temp/PluginWindow',
  'GOCAD_BUILD_PLATFORM' => 'Win_x64_6.1_v15',
  'GOCADROOT' => 'C:/Program Files/Paradigm/SKUA-GOCAD-18/Gocad',
  'GOCADPATH' => 'C:/temp/PluginWindow;C:/Program Files/Paradigm/SKUA-GOCAD-18/Gocad',
  'PROJECT_PATH' => [
    'C:/temp/PluginWindow',
    'C:/Program Files/Paradigm/SKUA-GOCAD-18/Gocad'
  ]
}
;

