REM Generated by configure.pl on Wed Sep 26 18:40:54 2018
REM DO NOT EDIT THIS FILE DIRECTLY!
REM Change settings and rerun configure.pl instead

set PROJECT_NAME=PluginWindow
set PROJECT_RELEASE_DATE=now
set PROJECT_BUILD_DATE=20180926
set PROJECT_BUILD_IDENTIFIER=20180926
set PROJECT_SOURCE_CONTROL_PATH=None
set PROJECT_REQUIRES=Gocad:3.0.0
set GOCADCONF=release-Win_x64_6.1_v15
set GOCADHOME=C:/temp/PluginWindow
set GOCADROOT=C:\Program Files\Paradigm\SKUA-GOCAD-18\Gocad
set GOCADPATH=C:/temp/PluginWindow;C:\Program Files\Paradigm\SKUA-GOCAD-18\Gocad
set GOCAD_OS=Win_x64_6.1
set GOCAD_GR=opengl
set GOCAD_CC=v15
set GOCAD_CCMODE=
set GOCAD_PLATFORM=Win_x64_6.1_v15
set GOCAD_TARGET=Win_x64_6.1_v15
set GOCAD_BUILD_PLATFORM=Win_x64_6.1_v15
set GOCAD_BUILD_TYPE=release

