@echo off
REM Command file for PluginWindow build environment
REM Generated by configure.pl on Wed Sep 26 18:40:54 2018
REM DO NOT EDIT THIS FILE DIRECTLY!
REM Change settings and rerun configure.pl instead

REM GOCADHOME, GOCADPATH and GOCADROOT are compulsory
set GOCADHOME=C:/temp/PluginWindow
set GOCADROOT=C:\Program Files\Paradigm\SKUA-GOCAD-18\Gocad
set GOCADPATH=C:/temp/PluginWindow;C:\Program Files\Paradigm\SKUA-GOCAD-18\Gocad
set GOCAD_BUILD_PLATFORM=Win_x64_6.1_v15
set GOCAD_BUILD_TYPE=release
set PDGM_PLUGIN_PATH=C:\Program Files\Paradigm\SKUA-GOCAD-18\Gocad\config;%PDGM_PLUGIN_PATH%
set PDGM_CATALOG_PATH=C:/temp/PluginWindow\config;%PDGM_CATALOG_PATH%

REM Setting Default OUTPUT_DIRECTORY when setenv.bat is called from the command line
if "%OUTPUT_DIRECTORY%" == "" (
    set OUTPUT_DIRECTORY=Win_x64_6.1_v15
)

REM Add platform specific include path first
set INCLUDE=%GOCADROOT%\include\platform\Win_x64_6.1_v15;%INCLUDE%

REM PluginWindow specific settings
set PluginWindow_HOME=C:/temp/PluginWindow
set PATH=%PluginWindow_HOME%\bin\%OUTPUT_DIRECTORY%;%PATH%
set LIB=%PluginWindow_HOME%\bin\%OUTPUT_DIRECTORY%;%LIB%
set INCLUDE=%PluginWindow_HOME%\include;%INCLUDE%

REM Special variable set for accessing Shared Build Tools in your suite.
set OPENGEO_DIR=S:\users\gdadmin\2018\project

REM Special variable set for accessing Shared Build Tools in your suite.
set LOCAL_SBT_PATH=S:\users\gdadmin\2018\project\src\SharedBuildTools

if exist "C:/temp/PluginWindow\devtools\custom-setenv-Win_x64_6.1_v15.bat" (
    call "C:/temp/PluginWindow\devtools\custom-setenv-Win_x64_6.1_v15.bat"
)

REM Gocad specific settings
set Gocad_HOME=C:\Program Files\Paradigm\SKUA-GOCAD-18\Gocad
set PATH=%Gocad_HOME%\bin\%OUTPUT_DIRECTORY%;%PATH%
set LIB=%Gocad_HOME%\bin\%OUTPUT_DIRECTORY%;%LIB%
set INCLUDE=%Gocad_HOME%\include;%INCLUDE%

REM Special variable set for accessing Shared Build Tools in your suite.
set OPENGEO_DIR=S:\users\gdadmin\2018\project

REM Special variable set for accessing Shared Build Tools in your suite.
set LOCAL_SBT_PATH=S:\users\gdadmin\2018\project\src\SharedBuildTools

if exist "C:\Program Files\Paradigm\SKUA-GOCAD-18\Gocad\devtools\custom-setenv-Win_x64_6.1_v15.bat" (
    call "C:\Program Files\Paradigm\SKUA-GOCAD-18\Gocad\devtools\custom-setenv-Win_x64_6.1_v15.bat"
)
