@echo off
REM This command file lets you start Visual Studio with the solution associated
REM to your plugin. Care is taken for setting environment correctly prior devenv call
REM Generated by configure.pl on Wed Sep 26 18:40:54 2018
REM DO NOT EDIT THIS FILE DIRECTLY!
REM Change settings and rerun configure.pl instead

SETLOCAL

REM This variable fix the performance issue when debugging from visual
REM See https://connect.microsoft.com/VisualStudio/feedback/details/401862/slow-deallocation-in-debug-mode-on-vista
REM Contrarily to what the name of this variable seems to mean,
REM setting it is _not_ disabling Debug version of heap, but is just
REM disabling some runtime checks that are expensive and not worth the price.
REM The main feature we are expecting from Debug Runtime remains active:
REM memory blocks are still filled with markers (0xdd,0xcd,0xff,etc.)
set _NO_DEBUG_HEAP=1

REM Change to directory of start-devenv so it can be run from anywhere


set OUTPUT_DIRECTORY=Win_x64_6.1_v15

call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
cd /d %~dp0
call "setenv-Win_x64_6.1_v15.bat"

devenv "%GOCADHOME%\PluginWindow.sln"
