#include <Gocad/xtools/xmglue.h>
#include <Gocad/xtools/xmpane.h>
#include <Gocad/xtools/xmscale.h>
#include <Gocad/xtools/xmbutton.h>
#include <Gocad/xtools/xwpixmap.h>
#include <Gocad/xtools/xwcursor.h>
#include <Gocad/xtools/xmdialog.h>
#include <Gocad/xtools/xmbox.h>
#include <Gocad/xtools/xmtextfield.h>
#include <Gocad/xtools/xmtext.h>
#include <Gocad/xtools/xmlabel.h>
#include <Gocad/xtools/xmmenu.h>
#include <Gocad/xtools/xmframe.h>
#include <Gocad/xtools/xmproxy.h>
#include <Gocad/xtools/xmseparator.h>
#include <Gocad/interpreter/gqselectors.h>
#include <Gocad/interpreter/valuator.h>
#include <Gocad/gui/sqlite/sqlviews_utils.h>
#include <Gocad/geobase/base/gobjmgr.h>
#include <Gocad/interpreter/cmdcreator.h>
#include <Gocad/interpreter/iparvalue.h>
#include <Gocad/interpreter/iparsurrogate.h>
#include <Gocad/interpreter/cmdexec.h>
#include <Gocad/interpreter/icstub.h>
#include <Gocad/interpreter/icmddef.h>
#include <Gocad/interpreter/cmdbrand.h>
#include <Gocad/gviews/pickvtools.h>
#include <Gocad/utils/gocad/gocadenv.h>
#include <Gocad/utils/misc/cstring.h>
#include <Gocad/utils/entity/entitylib.h>
#include <Gocad/qtools/gqlabel.h>
#include <Gocad/gui/sqlite/sqlselectors.h>
#include <Gocad/gui/sqlite/sqlselectors_initializers.h>
#include <Gocad/gui/sqlite/sqlselector_actions.h>
#include <Gocad/gui/sqlite/sqlutils.h>
#undef None

#include <xm_PluginWindow/xm_pluginwindowhellocommand.cpp>

